import "../styles/globals.scss";

import { Poppins } from "next/font/google";

import type { Metadata } from "next";

const poppins = Poppins({
  weight: ["400", "500"],
  preload: false,
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
