/*
|--------------------------------------------------------------------------
| レベル4の単語
|--------------------------------------------------------------------------
*/
import { Word } from '@/types/word';

const level4: Word[] = [
  {
    level: 4,
    kanji: "一富士二鷹三茄子",
    furigana: "いちふじにたかさんなすび",
    romaji: [
      "itifujinitakasannnasubi",
      "itihujinitakasannnasubi",
      "itifuzinitakasannnasubi",
      "itihuzinitakasannnasubi",
    ],
    score: 400,
  },
  {
    level: 4,
    kanji: "後は野となれ山となれ",
    furigana: "あとはのとなれやまとなれ",
    romaji: ["atohanotonareyamatonare"],
    score: 400,
  },
  {
    level: 4,
    kanji: "暑さ寒さも彼岸まで",
    furigana: "あつささむさもひがんまで",
    romaji: ["atusasamusamohiganmade"],
    score: 400,
  },
  {
    level: 4,
    kanji: "あちら立てればこちらが立たぬ",
    furigana: "あちらたてればこちらがたたぬ",
    romaji: ["atirataterebakotiragatatanu"],
    score: 400,
  },
  {
    level: 4,
    kanji: "当たるも八卦当たらぬも八卦",
    furigana: "あたるもはっけあたらぬもはっけ",
    romaji: ["atarumohakkeataranumohakke"],
    score: 400,
  },
  {
    level: 4,
    kanji: "一難去ってまた一難",
    furigana: "いちなんさってまたいちなん",
    romaji: ["itinannsattemataitinann"],
    score: 400,
  },
  {
    level: 4,
    kanji: "頭隠して尻隠さず",
    furigana: "あたまかくしてしりかくさず",
    romaji: ["atamakakusitesirikakusazu"],
    score: 400,
  },
  {
    level: 4,
    kanji: "秋茄子は嫁に食わすな",
    furigana: "あきなすはよめにくわすな",
    romaji: ["akinasuhayomenikuwasuna"],
    score: 400,
  },
  {
    level: 4,
    kanji: "一寸の虫にも五分の魂",
    furigana: "いっすんのむしにもごぶのたましい",
    romaji: ["issunnnomusinimogobunotamasii"],
    score: 400,
  },
  {
    level: 4,
    kanji: "魚心あれば水心",
    furigana: "うおごころあればみずごころ",
    romaji: ["uogokoroarebamizugokoro"],
    score: 400,
  },
  {
    level: 4,
    kanji: "牛にひかれて善光寺参り",
    furigana: "うしにひかれてぜんこうじまいり",
    romaji: ["usinihikaretezennkouzimairi", "usinihikaretezennkoujimairi"],
    score: 400,
  },
  {
    level: 4,
    kanji: "瓜の蔓に茄子はならぬ",
    furigana: "うりのつるになすびはならぬ",
    romaji: ["urinoturuninasubihanaranu"],
    score: 400,
  },
  {
    level: 4,
    kanji: "江戸の敵を長崎で討つ",
    furigana: "えどのかたきをながさきでうつ",
    romaji: ["edonokatakiwonagasakideutu"],
    score: 400,
  },
  {
    level: 4,
    kanji: "帯に短したすきに長し",
    furigana: "おびにみじかしたすきにながし",
    romaji: ["obinimizikasitasukininagasi", "obinimijikasitasukininagasi"],
    score: 400,
  },
  {
    level: 4,
    kanji: "溺れる者は藁をもつかむ",
    furigana: "おぼれるものはわらをもつかむ",
    romaji: ["oborerumonohawarawomotukamu"],
    score: 400,
  },
  {
    level: 4,
    kanji: "風が吹けば桶屋が儲かる",
    furigana: "かぜがふけばおけやがもうかる",
    romaji: ["kazeghukebaokeyagamoukaru", "kazegafukebaokeyagamoukaru"],
    score: 400,
  },
  {
    level: 4,
    kanji: "勝って兜の緒を締めよ",
    furigana: "かってかぶとのおをしめよ",
    romaji: ["kattekabutonoowosimeyo"],
    score: 400,
  },
  {
    level: 4,
    kanji: "壁に耳あり障子に目あり",
    furigana: "かべにみみありしょうじにめあり",
    romaji: [
      "kabenimimiarisyouzinimeari",
      "kabenimimiarishouzinimeari",
      "kabenimimiarisyoujinimeari",
      "kabenimimiarishoujinimeari",
    ],
    score: 400,
  },
  {
    level: 4,
    kanji: "清水の舞台から飛び降りる",
    furigana: "きよみずのぶたいからとびおりる",
    romaji: ["kiyomizunobutaikaratobioriru"],
    score: 400,
  },
  {
    level: 4,
    kanji: "孝行のしたい時分に親は無し",
    furigana: "こうこうのしたいじぶんにおやはなし",
    romaji: ["koukounositaijibunioyahanasi"],
    score: 400,
  },
  {
    level: 4,
    kanji: "郷に入っては郷に従え",
    furigana: "ごうにいってはごうにしたがえ",
    romaji: ["gouniittehagounisitagae"],
    score: 400,
  },
  {
    level: 4,
    kanji: "三人寄れば文殊の知恵",
    furigana: "さんにんよればもんじゅのちえ",
    romaji: ["sannninyorebamonzyunotie", "sannninyorebamonjunotie"],
    score: 400,
  },
  {
    level: 4,
    kanji: "泰山鳴動して鼠一匹",
    furigana: "たいざんめいどうしてねずみいっぴき",
    romaji: ["taizannmeidousitenezumiippiki"],
    score: 400,
  },
  {
    level: 4,
    kanji: "柿檀は双葉より芳し",
    furigana: "せんだんはふたばよりかんばし",
    romaji: ["senndannhahutabayorikannbasi", "senndannhafutabayorikannbasi"],
    score: 400,
  },
  {
    level: 4,
    kanji: "立っているものは親でも使え",
    furigana: "たっているものはおやでもつかえ",
    romaji: ["tatteirumonohaoyademotukae"],
    score: 400,
  },
  {
    level: 4,
    kanji: "玉磨かざれば光なし",
    furigana: "たまみがかざればひかりなし",
    romaji: ["tamamigakazarebahikarinasi"],
    score: 400,
  },
  {
    level: 4,
    kanji: "沈黙は金、雄弁は銀",
    furigana: "ちんもくはきん、ゆうべんはぎん",
    romaji: ["tinnmokuhakinn,yuubennhaginn"],
    score: 400,
  },
  {
    level: 4,
    kanji: "鶴は千年、亀は万年",
    furigana: "つるはせんねん、かめはまんねん",
    romaji: ["turuhasennnen,kamehamannnenn"],
    score: 400,
  },
  {
    level: 4,
    kanji: "角を矯めて牛を殺す",
    furigana: "つのをためてうしをころす",
    romaji: ["tunowotameteusiwokorosu"],
    score: 400,
  },
  {
    level: 4,
    kanji: "生兵法は大怪我の元",
    furigana: "なまびょうほうはおおけがのもと",
    romaji: ["namabyouhouhaookeganomoto"],
    score: 400,
  },
  {
    level: 4,
    kanji: "急け者の節句働き",
    furigana: "なまけもののせっくばたらき",
    romaji: ["namakemononosekkubataraki"],
    score: 400,
  },
  {
    level: 4,
    kanji: "泣く子と地頭には勝てぬ",
    furigana: "なくことじとうにはかてぬ",
    romaji: ["nakukotozitounihakatenu", "nakukotojitounihakatenu"],
    score: 400,
  },
  {
    level: 4,
    kanji: "飛んで火にいる夏の虫",
    furigana: "とんでひにいるなつのむし",
    romaji: ["tonndehiniirunatunomusi"],
    score: 400,
  },
  {
    level: 4,
    kanji: "遠い親戚より近くの他人",
    furigana: "とおいしんせきよりちかくのたにん",
    romaji: ["tooisinnsekiyoritikakunotaninn"],
    score: 400,
  },
  {
    level: 4,
    kanji: "人のふり見てわがふり直せ",
    furigana: "ひとのふりみてわがふりなおせ",
    romaji: [
      "hitonohurimitewagahurinaose",
      "hitonohurimitewagafurinaose",
      "hitonofurimitewagafurinaose",
      "hitonofurimitewagahurinaose",
    ],
    score: 400,
  },
  {
    level: 4,
    kanji: "人の口には戸が立てられない",
    furigana: "ひとのくちにはとがたてられない",
    romaji: ["hitonokutinihatogataterarenai"],
    score: 400,
  },
  {
    level: 4,
    kanji: "人のうわさも七十五日",
    furigana: "ひとのうわさもしちじゅうごにち",
    romaji: ["hitonouwasamositizyuugoniti", "hitonouwasamositijuugoniti"],
    score: 400,
  },
  {
    level: 4,
    kanji: "腹八分目に医者いらず",
    furigana: "はらはちぶんめにいしゃいらず",
    romaji: ["harahatibumeniisyairazu", "harahatibumeniishairazu"],
    score: 400,
  },
  {
    level: 4,
    kanji: "喉元過ぎれば熱さを忘れる",
    furigana: "のどもとすぎればあつさをわすれる",
    romaji: ["nodomotosugirebaatusawasureru"],
    score: 400,
  },
  {
    level: 4,
    kanji: "能ある鷹は爪を隠す",
    furigana: "のうあるたかはつめをかくす",
    romaji: ["nouarutakahatumewokakusu"],
    score: 400,
  },
  {
    level: 4,
    kanji: "二兎を追うものは一兎をも得ず",
    furigana: "にとをおうものはいっとをもえず",
    romaji: ["nitowooumohaittowomoezu"],
    score: 400,
  },
  {
    level: 4,
    kanji: "人を見たら泥棒と思え",
    furigana: "ひとをみたらどろぼうとおもえ",
    romaji: ["hitowomitaradoroboutomoe"],
    score: 400,
  },
  {
    level: 4,
    kanji: "火のない所に煙は立たぬ",
    furigana: "ひのないところにけむりはたたぬ",
    romaji: ["hinonaitokoronikemurihatatanu"],
    score: 400,
  },
  {
    level: 4,
    kanji: "夫婦喧嘩は犬も食わない",
    furigana: "ふうふげんかはいぬもくわない",
    romaji: [
      "huuhugenkahainumokuwanai",
      "huufugenkahainumokuwanai",
      "fuufugenkahainumokuwanai",
      "fuuhugenkahainumokuwanai",
    ],
    score: 400,
  },
  {
    level: 4,
    kanji: "下手な鉄砲も数撃ちゃ当たる",
    furigana: "へたなてっぽうもかずうちゃあたる",
    romaji: ["hetanateppoumokazuutyaataru"],
    score: 400,
  },
  {
    level: 4,
    kanji: "下手の考え休むに似たり",
    furigana: "へたのかんがえやすむににたり",
    romaji: ["hetanokangaeyasumuninitari"],
    score: 400,
  },
  {
    level: 4,
    kanji: "骨折り損のくたびれもうけ",
    furigana: "ほねおりぞんのくたびれもうけ",
    romaji: ["honeorizonnnokutabiremouke"],
    score: 400,
  },
  {
    level: 4,
    kanji: "安物買いの銭失い",
    furigana: "やすものかいのぜにうしない",
    romaji: ["yasumonokainozeniusinai"],
    score: 400,
  },
  {
    level: 4,
    kanji: "物言えば唇寒し秋の風",
    furigana: "ものいえばくちびるさむしあきのかぜ",
    romaji: ["monoiebakutibirusamusiakinokaze"],
    score: 400,
  },
  {
    level: 4,
    kanji: "無理が通れば道理引っ込む",
    furigana: "むりがとおればどうりひっこむ",
    romaji: ["murigatoorebadourihikkomu"],
    score: 400,
  },
  {
    level: 4,
    kanji: "実るほど頭の下がる稲穂かな",
    furigana: "みのるほどあたまのさがるいなほかな",
    romaji: ["minoruhodoatamanosagaruinahokana"],
    score: 400,
  },
  {
    level: 4,
    kanji: "丸い卵も切りようで四角",
    furigana: "まるいたまごもきりようでしかく",
    romaji: ["maruitamagomokiriyoudesikaku"],
    score: 400,
  },
  {
    level: 4,
    kanji: "柳の下にいつもどじょうはいない",
    furigana: "やなぎのしたにいつもどじょうはいない",
    romaji: [
      "yanaginositaniitumodozyouhainai",
      "yanaginositaniitumodojouhainai",
    ],
    score: 400,
  },
  {
    level: 4,
    kanji: "よしの髄から天井をのぞく",
    furigana: "よしのずいからてんじょうをのぞく",
    romaji: ["yosinozuikaratenzyouwonozoku", "yosinozuikaratenjouwonozoku"],
    score: 400,
  },
  {
    level: 4,
    kanji: "来年のことを言えば鬼が笑う",
    furigana: "らいねんのことをいえばおにがわらう",
    romaji: ["rainennnokotowoiebaonigawarau"],
    score: 400,
  },
  {
    level: 4,
    kanji: "楽あれば苦あり、苦は楽の種",
    furigana: "らくあればくあり、くはらくのたね",
    romaji: ["rakuarebakuari,kuharakunotane"],
    score: 400,
  },
  {
    level: 4,
    kanji: "瑠璃も玻璃も照らせば光る",
    furigana: "るりもはりもてらせばひかる",
    romaji: ["rurimoharimoterasebahikaru"],
    score: 400,
  },
  {
    level: 4,
    kanji: "論語読みの論語知らず",
    furigana: "ろんごよみのろんごしらず",
    romaji: ["ronngoyominoronngosirazu"],
    score: 400,
  },
];

export default level4;
