/*
|--------------------------------------------------------------------------
| レベル2の単語
|--------------------------------------------------------------------------
*/
import { Word } from "@/types/word";

const level2: Word[] = [
  {
    level: 2,
    kanji: "棚からぼた餅",
    furigana: "たなからぼたもち",
    romaji: ["tanakarabotamoti"],
    score: 200,
  },
  {
    level: 2,
    kanji: "灯台下暗し",
    furigana: "とうだいもとくらし",
    romaji: ["toudaimotokurasi"],
    score: 200,
  },
  {
    level: 2,
    kanji: "一事が万事",
    furigana: "いちじがばんじ",
    romaji: [
      "itizigabannzi",
      "itizigabannji",
      "itijigabannzi",
      "itijigabannji",
    ],
  },
  {
    level: 2,
    kanji: "医者の不養生",
    furigana: "いしゃのふようじょう",
    romaji: [
      "ishanofuyoujou",
      "isyanofuyoujou",
      "ishanofuyouzyou",
      "isyanofuyouzyou",
    ],
  },
  {
    level: 2,
    kanji: "石の上にも三年",
    furigana: "いしのうえにもさんねん",
    romaji: ["isinouenimosannnenn"],
    score: 200,
  },
  {
    level: 2,
    kanji: "一寸先は闇",
    furigana: "いっすんさきはやみ",
    romaji: ["issunnsakihayami"],
    score: 200,
  },
  {
    level: 2,
    kanji: "嘘から出た誠",
    furigana: "うそからでたまこと",
    romaji: ["usokaradetamakoto"],
    score: 200,
  },
  {
    level: 2,
    kanji: "噂をすれば影",
    furigana: "うわさをすればかげ",
    romaji: ["uwasawosurebakage"],
    score: 200,
  },
  {
    level: 2,
    kanji: "小田原評定",
    furigana: "おだわらひょうじょう",
    romaji: ["odawarahyouzyou"],
    score: 200,
  },
  {
    level: 2,
    kanji: "海老で鯛を釣る",
    furigana: "えびでたいをつる",
    romaji: ["ebidetaiwoturu"],
    score: 200,
  },
  {
    level: 2,
    kanji: "鬼の目にも涙",
    furigana: "おにのめにもなみだ",
    romaji: ["oninomenimonamida"],
    score: 200,
  },
  {
    level: 2,
    kanji: "蛙の子は蛙",
    furigana: "かえるのこはかえる",
    romaji: ["kaerunokohakaeru"],
    score: 200,
  },
  {
    level: 2,
    kanji: "蛙の面に水",
    furigana: "かえるのつらにみず",
    romaji: ["kaerunoturanimizu"],
    score: 200,
  },
  {
    level: 2,
    kanji: "河童の川流れ",
    furigana: "かっぱのかわながれ",
    romaji: ["kappanokawanagare"],
    score: 200,
  },
  {
    level: 2,
    kanji: "果報は寝て待て",
    furigana: "かほうはねてまて",
    romaji: ["kahouwanetemate"],
    score: 200,
  },
  {
    level: 2,
    kanji: "木を見て森を見ず",
    furigana: "きをみてもりをみず",
    romaji: ["kiwomitemoriwomizu"],
    score: 200,
  },
  {
    level: 2,
    kanji: "苦しい時の神頼み",
    furigana: "くるしいときのかみだのみ",
    romaji: ["kurusiitokinokamidonomi"],
    score: 200,
  },
  {
    level: 2,
    kanji: "芸は身を助ける",
    furigana: "げいはみをたすける",
    romaji: ["geihamiwotasukeru"],
    score: 200,
  },
  {
    level: 2,
    kanji: "口は災いの元",
    furigana: "くちはわざわいのもと",
    romaji: ["kutiwawazawainomoto"],
    score: 200,
  },
  {
    level: 2,
    kanji: "光陰矢のごとし",
    furigana: "こういんやのごとし",
    romaji: ["kouinnyanogotosi"],
    score: 200,
  },
  {
    level: 2,
    kanji: "後悔先に立たず",
    furigana: "こうかいさきにたたず",
    romaji: ["koukaisakinitatazu"],
    score: 200,
  },
  {
    level: 2,
    kanji: "弘法筆を選ばず",
    furigana: "こうぼうふでをえらばず",
    romaji: ["koubouhudewoerabazu", "kouboufudewoerabazu"],
    score: 200,
  },
  {
    level: 2,
    kanji: "紺屋の白袴",
    furigana: "こうやのしろばかま",
    romaji: ["kouyanosirobakama"],
    score: 200,
  },
  {
    level: 2,
    kanji: "転ばぬ先の杖",
    furigana: "ころばぬさきのつえ",
    romaji: ["korobanusakinotue"],
    score: 200,
  },
  {
    level: 2,
    kanji: "先んずれば人を制す",
    furigana: "さきんずればひとをせいす",
    romaji: ["sakinnzurebahitowoseisu"],
    score: 200,
  },
  {
    level: 2,
    kanji: "猿も木から落ちる",
    furigana: "さるもきからおちる",
    romaji: ["sarumokikaraotiru"],
    score: 200,
  },
  {
    level: 2,
    kanji: "失敗は成功の基",
    furigana: "しっぱいはせいこうのもと",
    romaji: ["sippaiwaseikounomoto"],
    score: 200,
  },
  {
    level: 2,
    kanji: "初心忘るべからず",
    furigana: "しょしんわするべからず",
    romaji: ["syosinnwasurubekarazu", "shosinnwasurubekarazu"],
    score: 200,
  },
  {
    level: 2,
    kanji: "立つ鳥跡を濁さず",
    furigana: "たつとりあとをにごさず",
    romaji: ["tatutoriatowonigosazu"],
    score: 200,
  },
  {
    level: 2,
    kanji: "旅の恥はかき捨て",
    furigana: "たびのはじはかきすて",
    romaji: ["tabinohazihakakisute", "tabinohajihakakisute"],
    score: 200,
  },
  {
    level: 2,
    kanji: "提灯に釣り鐘",
    furigana: "ちょうちんにつりがね",
    romaji: ["tyoutinnniturigane"],
    score: 200,
  },
  {
    level: 2,
    kanji: "出る杭は打たれる",
    furigana: "でるくいはうたれる",
    romaji: ["derukuihautareru"],
    score: 200,
  },
  {
    level: 2,
    kanji: "天は二物を与えず",
    furigana: "てんはにぶつをあたえず",
    romaji: ["tennhanibutuwotaezu"],
    score: 200,
  },
  {
    level: 2,
    kanji: "習うより慣れろ",
    furigana: "ならうよりなれろ",
    romaji: ["narauyorinarero"],
    score: 200,
  },
  {
    level: 2,
    kanji: "七転び八起き",
    furigana: "ななころびやおき",
    romaji: ["nanakorobiyaoki"],
    score: 200,
  },
  {
    level: 2,
    kanji: "泣きっ面に蜂",
    furigana: "なきっつらにはち",
    romaji: ["nakitturanihati"],
    score: 200,
  },
  {
    level: 2,
    kanji: "鳶が鷹を生む",
    furigana: "とびがたかをうむ",
    romaji: ["tobigatakawoumu"],
    score: 200,
  },
  {
    level: 2,
    kanji: "隣の花は赤い",
    furigana: "となりのはなはあかい",
    romaji: ["tonarinohanahaakai"],
    score: 200,
  },
  {
    level: 2,
    kanji: "年寄りの冷や水",
    furigana: "としよりのひやみず",
    romaji: ["tosiyorinohiyamizu"],
    score: 200,
  },
  {
    level: 2,
    kanji: "豆腐にかすがい",
    furigana: "とうふにかすがい",
    romaji: ["touhunikasugai", "toufunikasugai"],
    score: 200,
  },
  {
    level: 2,
    kanji: "必要は発明の母",
    furigana: "ひつようははつめいのはは",
    romaji: ["hituyouhahatumeinohaha"],
    score: 200,
  },
  {
    level: 2,
    kanji: "暖簾に腕押し",
    furigana: "のれんにうでおし",
    romaji: ["norennniudeosi"],
    score: 200,
  },
  {
    level: 2,
    kanji: "逃がした魚は大きい",
    furigana: "にがしたさかなはおおきい",
    romaji: ["nigasitasakanahaookii"],
    score: 200,
  },
  {
    level: 2,
    kanji: "二階から目薬",
    furigana: "にかいからめぐすり",
    romaji: ["nikaikaramagusuri"],
    score: 200,
  },
  {
    level: 2,
    kanji: "貧すれば鈍する",
    furigana: "ひんすればどんする",
    romaji: ["hinsurebadonnsuru"],
    score: 200,
  },
  {
    level: 2,
    kanji: "蛇ににらまれた蛙",
    furigana: "へびににらまれたかえる",
    romaji: ["hebininiramaretakaeru"],
    score: 200,
  },
  {
    level: 2,
    kanji: "仏の顔も三度",
    furigana: "ほとけのかおもさんど",
    romaji: ["hotokenokaomosanndo"],
    score: 200,
  },
  {
    level: 2,
    kanji: "まかぬ種は生えぬ",
    furigana: "まかぬたねははえぬ",
    romaji: ["makanutanehahainu"],
    score: 200,
  },
  {
    level: 2,
    kanji: "昔取った杵柄",
    furigana: "むかしとったきねづか",
    romaji: ["mukasitottakineduka"],
    score: 200,
  },
  {
    level: 2,
    kanji: "弱り目に祟り目",
    furigana: "よわりめにたたりめ",
    romaji: ["yowarimenitatarime"],
    score: 200,
  },
  {
    level: 2,
    kanji: "類は友を呼ぶ",
    furigana: "るいはともをよぶ",
    romaji: ["ruihatomowoyobu"],
    score: 200,
  },
  {
    level: 2,
    kanji: "破れ鍋に綴じ蓋",
    furigana: "われなべにとじぶた",
    romaji: ["warenabenitozibuta", "warenabenitojibuta"],
    score: 200,
  },
];

export default level2;
