/*
|--------------------------------------------------------------------------
| レベル1の単語
|--------------------------------------------------------------------------
*/
import { Word } from '@/types/word';

const level1: Word[] = [
  {
    level: 1,
    kanji: "善は急げ",
    furigana: "ぜんはいそげ",
    romaji: ["zennhaisoge"],
    score: 100,
  },
  {
    level: 1,
    kanji: "糠に釘",
    furigana: "ぬかにくぎ",
    romaji: ["nukanikugi"],
    score: 100,
  },
  {
    level: 1,
    kanji: "痩せの大食い",
    furigana: "やせのおおぐい",
    romaji: ["yasenooogui"],
    score: 100,
  },
  {
    level: 1,
    kanji: "犬猿の仲",
    furigana: "けんえんのなか",
    romaji: ["kennennnonaka"],
    score: 100,
  },
  {
    level: 1,
    kanji: "猫に小判",
    furigana: "ねこにこばん",
    romaji: ["nekonikobann"],
    score: 100,
  },
  {
    level: 1,
    kanji: "言わぬが花",
    furigana: "いわぬがはな",
    romaji: ["iwanugahana"],
    score: 100,
  },
  {
    level: 1,
    kanji: "嘘も方便",
    furigana: "うそもほうべん",
    romaji: ["usomohoubenn"],
    score: 100,
  },
  {
    level: 1,
    kanji: "鬼に金棒",
    furigana: "おににかなぼう",
    romaji: ["oninikanabou"],
    score: 100,
  },
  {
    level: 1,
    kanji: "鬼の霍乱",
    furigana: "おにのかくらん",
    romaji: ["oninokakurann"],
    score: 100,
  },
  {
    level: 1,
    kanji: "勝てば官軍",
    furigana: "かてばかんぐん",
    romaji: ["katebakangunn"],
    score: 100,
  },
  {
    level: 1,
    kanji: "腐っても鯛",
    furigana: "くさってもたい",
    romaji: ["kusattemotai"],
    score: 100,
  },
  {
    level: 1,
    kanji: "住めば都",
    furigana: "すめばみやこ",
    romaji: ["sumebamiyako"],
    score: 100,
  },
  {
    level: 1,
    kanji: "短気は損気",
    furigana: "たんきはそんき",
    romaji: ["tannkihasonnki"],
    score: 100,
  },
  {
    level: 1,
    kanji: "月とすっぽん",
    furigana: "つきとすっぽん",
    romaji: ["tukitosupponn"],
    score: 100,
  },
  {
    level: 1,
    kanji: "逃げるが勝ち",
    furigana: "にげるがかち",
    romaji: ["nigerugakati"],
    score: 100,
  },
  {
    level: 1,
    kanji: "豚に真珠",
    furigana: "ぶたにしんじゅ",
    romaji: ["butanisinju", "butanisinzyu"],
    score: 100,
  },
  {
    level: 1,
    kanji: "あばたもえくぼ",
    furigana: "あばたもえくぼ",
    romaji: ["abatamoekubo"],
    score: 100,
  },
  {
    level: 1,
    kanji: "餅は餅屋",
    furigana: "もちはもちや",
    romaji: ["motihamotiya"],
    score: 100,
  },
  {
    level: 1,
    kanji: "目の上のこぶ",
    furigana: "めのうえのこぶ",
    romaji: ["menouenokobu"],
    score: 100,
  },
  {
    level: 1,
    kanji: "花より団子",
    furigana: "はなよりだんご",
    romaji: ["hanayoridango"],
    score: 100,
  },
  {
    level: 1,
    kanji: "氏より育ち",
    furigana: "うじよりそだち",
    romaji: ["uziyorisodati", "ujiyorisodati"],
    score: 100,
  },
  {
    level: 1,
    kanji: "虻蜂取らず",
    furigana: "あぶはちとらず",
    romaji: ["abuhatitorazu"],
    score: 100,
  },
  {
    level: 1,
    kanji: "急がば回れ",
    furigana: "いそがばまわれ",
    romaji: ["isogabamaware"],
    score: 100,
  },
  {
    level: 1,
    kanji: "病は気から",
    furigana: "やまいはきから",
    romaji: ["yamaihakikara"],
    score: 100,
  },
  {
    level: 1,
    kanji: "時は金なり",
    furigana: "ときはかねなり",
    romaji: ["tokihakanenari"],
    score: 100,
  },
  {
    level: 1,
    kanji: "貧乏暇なし",
    furigana: "びんぼうひまなし",
    romaji: ["binnbouhimanasi"],
    score: 100,
  },
  {
    level: 1,
    kanji: "なくて七癖",
    furigana: "なくてななくせ",
    romaji: ["nakutenanakuse"],
    score: 100,
  },
  {
    level: 1,
    kanji: "知らぬが仏",
    furigana: "しらぬがほとけ",
    romaji: ["siranugahotoke"],
    score: 100,
  },
  {
    level: 1,
    kanji: "身から出たさび",
    furigana: "みからでたさび",
    romaji: ["mikaradetasabi"],
    score: 100,
  },
  {
    level: 1,
    kanji: "論より証拠",
    furigana: "ろんよりしょうこ",
    romaji: ["ronnyorisyouko"],
    score: 100,
  },
  {
    level: 1,
    kanji: "元の木阿弥",
    furigana: "もとのもくあみ",
    romaji: ["motonomokuami"],
    score: 100,
  },
];

export default level1;
