import { Word } from "@/types/word";

const level24: Word[] = [
  { kanji: "本日", furigana: "ほんじつ", romaji: "honjitsu" },
  { kanji: "家族", furigana: "かぞく", romaji: "kazoku" },
  { kanji: "学校", furigana: "がっこう", romaji: "gakkou" },
  { kanji: "公園", furigana: "こうえん", romaji: "kouen" },
  { kanji: "駅", furigana: "えき", romaji: "eki" },
  { kanji: "電車", furigana: "でんしゃ", romaji: "densha" },
  { kanji: "バス", furigana: "ばす", romaji: "basu" },
  { kanji: "車", furigana: "くるま", romaji: "kuruma" },
  { kanji: "旅行", furigana: "りょこう", romaji: "ryokou" },
  { kanji: "映画", furigana: "えいが", romaji: "eiga" },
  { kanji: "音楽", furigana: "おんがく", romaji: "ongaku" },
  { kanji: "料理", furigana: "りょうり", romaji: "ryouri" },
  { kanji: "運動", furigana: "うんどう", romaji: "undou" },
  { kanji: "勉強", furigana: "べんきょう", romaji: "benkyou" },
  { kanji: "掃除", furigana: "そうじ", romaji: "souji" },
  { kanji: "洗濯", furigana: "せんたく", romaji: "sentaku" },
  { kanji: "買い物", furigana: "かいもの", romaji: "kaimono" },
  { kanji: "食事", furigana: "しょくじ", romaji: "shokuji" },
  { kanji: "飲み会", furigana: "のみかい", romaji: "nomikai" },
  { kanji: "仕事", furigana: "しごと", romaji: "shigoto" },
  { kanji: "休み", furigana: "やすみ", romaji: "yasumi" },
  { kanji: "元気", furigana: "げんき", romaji: "genki" },
  { kanji: "楽しい", furigana: "たのしい", romaji: "tanoshii" },
  { kanji: "嬉しい", furigana: "うれしい", romaji: "ureshii" },
  { kanji: "風船", furigana: "ふうせん", romaji: "fuusen" },
  { kanji: "犬", furigana: "いぬ", romaji: "inu" },
  { kanji: "猫", furigana: "ねこ", romaji: "neko" },
  { kanji: "鳥", furigana: "とり", romaji: "tori" },
  { kanji: "魚", furigana: "さかな", romaji: "sakana" },
  { kanji: "熊", furigana: "くま", romaji: "kuma" },
  { kanji: "猿", furigana: "さる", romaji: "saru" },
  { kanji: "狼", furigana: "おおかみ", romaji: "ookami" },
  { kanji: "虎", furigana: "とら", romaji: "tora" },
  { kanji: "獅子", furigana: "しし", romaji: "shishi" },
];

export default level24;
