/*
|--------------------------------------------------------------------------
| レベル3の単語
|--------------------------------------------------------------------------
*/
import { Word } from '@/types/word';

const level3: Word[] = [
  {
    level: 3,
    kanji: "いすれ菖蒲か杜若",
    furigana: "いすれあやめかかきつばた",
    romaji: ["isureayamekakakitubata"],
    score: 300,
  },
  {
    level: 3,
    kanji: "石橋をたたいて渡る",
    furigana: "いしばしをたたいてわたる",
    romaji: ["isibasiwotataitewataru"],
    score: 300,
  },
  {
    level: 3,
    kanji: "雨降って地固まる",
    furigana: "あめふってじかたまる",
    romaji: [
      "amefuttezikatamaru",
      "amefuttejikatamaru",
      "amehuttezikatamaru",
      "amehuttejikatamaru",
    ],
  },
  {
    level: 3,
    kanji: "頭の上の蝿を追え",
    furigana: "あたまのうえのはえをおえ",
    romaji: ["atamanouenohaewooe"],
    score: 300,
  },
  {
    level: 3,
    kanji: "会うは別れの始め",
    furigana: "あうはわかれのはじめ",
    romaji: ["auhawakarenohazime", "auhawakarenohajime"],
    score: 300,
  },
  {
    level: 3,
    kanji: "鵜の真似をする烏",
    furigana: "うのまねをするからす",
    romaji: ["unomanewosurukarasu"],
    score: 300,
  },
  {
    level: 3,
    kanji: "馬の耳に念仏",
    furigana: "うまのみみにねんぶつ",
    romaji: ["umanomimininennbutu"],
    score: 300,
  },
  {
    level: 3,
    kanji: "鬼の居ぬ間に洗濯",
    furigana: "おにのいぬまにせんたく",
    romaji: ["oninoinumanisenntaku"],
    score: 300,
  },
  {
    level: 3,
    kanji: "驕る平家は久しからず",
    furigana: "おごるへいけはひさしからず",
    romaji: ["ogoruheikehahisasikarazu"],
    score: 300,
  },
  {
    level: 3,
    kanji: "縁の下の力持ち",
    furigana: "えんのしたのちからもち",
    romaji: ["ennnositanotikaramoti"],
    score: 300,
  },
  {
    level: 3,
    kanji: "親の心子知らず",
    furigana: "おやのこころこしらず",
    romaji: ["oyanokokorokosirazu"],
    score: 300,
  },
  {
    level: 3,
    kanji: "風邪は万病の元",
    furigana: "かぜはまんびょうのもと",
    romaji: ["kazewamannbyounomoto"],
    score: 300,
  },
  {
    level: 3,
    kanji: "金は天下の回りもの",
    furigana: "かねはてんかのまわりもの",
    romaji: ["kanehatennkanomawarimono"],
    score: 300,
  },
  {
    level: 3,
    kanji: "亀の甲より年の功",
    furigana: "かめのこうよりとしのこう",
    romaji: ["kamenokouyoritosinokou"],
    score: 300,
  },
  {
    level: 3,
    kanji: "鴨が葱を背負ってくる",
    furigana: "かもがねぎをしょってくる",
    romaji: ["kamoganegiwosyottekuru", "kamoganegiwoshottekuru"],
    score: 300,
  },
  {
    level: 3,
    kanji: "枯れ木も山の賑わい",
    furigana: "かれきもやまのにぎわい",
    romaji: ["karekimoyamanonigiwai"],
    score: 300,
  },
  {
    level: 3,
    kanji: "雉も鳴かずば撃たれまい",
    furigana: "きじもなかずばうたれまい",
    romaji: ["kizimonakazubautaremai", "kijimonakazubautaremai"],
    score: 300,
  },
  {
    level: 3,
    kanji: "九死に一生を得る",
    furigana: "きゅうしにいっしょうをえる",
    romaji: ["kyuusiniissyouwoeru", "kyuusiniisshouwoeru"],
    score: 300,
  },
  {
    level: 3,
    kanji: "君子危うきに近寄らず",
    furigana: "くんしあやうきにちかよらず",
    romaji: ["kunsiayaukinitikayorazu"],
    score: 300,
  },
  {
    level: 3,
    kanji: "聞いて極楽見て地獄",
    furigana: "きいてごくらくみてじごく",
    romaji: ["kiitegokurakumitezigoku", "kiitegokurakumitejigoku"],
    score: 300,
  },
  {
    level: 3,
    kanji: "弘法にも筆の誤り",
    furigana: "こうぼうにもふでのあやまり",
    romaji: ["koubounimohudenoayamari", "koubounimofudenoayamari"],
    score: 300,
  },
  {
    level: 3,
    kanji: "触らぬ神に祟りなし",
    furigana: "さわらぬかみにたたりなし",
    romaji: ["sawaranukaminitatarinasi"],
    score: 300,
  },
  {
    level: 3,
    kanji: "袖振り合うも多生の縁",
    furigana: "そでふりあうもたしょうのえん",
    romaji: [
      "sodehuriaumotasyounoenn",
      "sodehuriaumotashounoenn",
      "sodefuriaumotasyounoenn",
      "sodefuriaumotashounoenn",
    ],
  },
  {
    level: 3,
    kanji: "地獄の沙汰も金次第",
    furigana: "じごくのさたもかねしだい",
    romaji: ["zigokunosatamokanesidai", "jigokunosatamokanesidai"],
    score: 300,
  },
  {
    level: 3,
    kanji: "親しき仲にも礼儀あり",
    furigana: "したしきなかにもれいぎあり",
    romaji: ["sitasikinakanimoreigiari"],
    score: 300,
  },
  {
    level: 3,
    kanji: "朱に交われば赤くなる",
    furigana: "しゅにまじわればあかくなる",
    romaji: [
      "syunimaziwarebaakakunaru",
      "shunimaziwarebaakakunaru",
      "syunimajiwarebaakakunaru",
      "shunimajiwarebaakakunaru",
    ],
  },
  {
    level: 3,
    kanji: "好きこそものの上手なれ",
    furigana: "すきこそもののじょうずなれ",
    romaji: ["sukikosomononozyouzunare", "sukikosomononojouzunare"],
    score: 300,
  },
  {
    level: 3,
    kanji: "急いては事を仕損じる",
    furigana: "せいてはことをしそんじる",
    romaji: ["seitohakotowosisonnziru", "seitohakotowosisonnjiru"],
    score: 300,
  },
  {
    level: 3,
    kanji: "案ずるより産むが易し",
    furigana: "あんずるよりうむがやすし",
    romaji: ["annzuruyoriumugayasusi"],
    score: 300,
  },
  {
    level: 3,
    kanji: "ただより高いものはない",
    furigana: "ただよりたかいものはない",
    romaji: ["tadayoritakaimonohanai"],
    score: 300,
  },
  {
    level: 3,
    kanji: "蓼食う虫も好き好き",
    furigana: "たでくうむしもすきずき",
    romaji: ["tadekuumusimosukizuki"],
    score: 300,
  },
  {
    level: 3,
    kanji: "旅は道連れ世は情け",
    furigana: "たびはみちづれよはなさけ",
    romaji: ["tabihamitizureyohanasake"],
    score: 300,
  },
  {
    level: 3,
    kanji: "鉄は熱いうちに打て",
    furigana: "てつはあついうちにうて",
    romaji: ["tetuhaatuiutiniute"],
    score: 300,
  },
  {
    level: 3,
    kanji: "情けは人のためならず",
    furigana: "なさけはひとのためならず",
    romaji: ["nasakehahitonotamenarazu"],
    score: 300,
  },
  {
    level: 3,
    kanji: "長いものには巻かれろ",
    furigana: "ながいものにはまかれろ",
    romaji: ["nagaimononihamakarero"],
    score: 300,
  },
  {
    level: 3,
    kanji: "どんぐりの背比べ",
    furigana: "どんぐりのせいくらべ",
    romaji: ["donngurinoseikurabe"],
    score: 300,
  },
  {
    level: 3,
    kanji: "所変われば品変わる",
    furigana: "ところかわればしなかわる",
    romaji: ["tokorokawarebasinakawaru"],
    score: 300,
  },
  {
    level: 3,
    kanji: "人は見かけによらぬもの",
    furigana: "ひとはみかけによらぬもの",
    romaji: ["hitohamikakeniyoranumono"],
    score: 300,
  },
  {
    level: 3,
    kanji: "早起きは三文の徳",
    furigana: "はやおきはさんもんのとく",
    romaji: ["hayaokihasannmonnotoku"],
    score: 300,
  },
  {
    level: 3,
    kanji: "憎まれっ子世にはばかる",
    furigana: "にくまれっこよにはばかる",
    romaji: ["nikumarekkoyonihabakaru"],
    score: 300,
  },
  {
    level: 3,
    kanji: "人を呪わば穴二つ",
    furigana: "ひとをのろわばあなふたつ",
    romaji: ["hitowonorowabaanahutatu", "hitowonorowabaanafutatu"],
    score: 300,
  },
  {
    level: 3,
    kanji: "百害あって一利なし",
    furigana: "ひゃくがいあっていちりなし",
    romaji: ["hyakugaiatteitirinasi"],
    score: 300,
  },
  {
    level: 3,
    kanji: "笛吹けども踊らず",
    furigana: "ふえふけどもおどらず",
    romaji: [
      "huehukedomoodorazu",
      "huefukedomoodorazu",
      "fuehukedomoodorazu",
      "fuefukedomoodorazu",
    ],
  },
  {
    level: 3,
    kanji: "ペンは剣よりも強し",
    furigana: "ぺんはけんよりもつよし",
    romaji: ["pennhakennyorimotuyosi"],
    score: 300,
  },
  {
    level: 3,
    kanji: "仏作って魂入れず",
    furigana: "ほとけつくってたましいいれず",
    romaji: ["hotoketukuttetamasiirezu"],
    score: 300,
  },
  {
    level: 3,
    kanji: "目は口ほどにものを言う",
    furigana: "めはくちほどにものをいう",
    romaji: ["mehakutihodonimonowoiu"],
    score: 300,
  },
  {
    level: 3,
    kanji: "目くそ鼻くそを笑う",
    furigana: "めくそはなくそをわらう",
    romaji: ["mekusohanakusowowarau"],
    score: 300,
  },
  {
    level: 3,
    kanji: "身を捨ててこそ浮かぶ瀬もあれ",
    furigana: "みをすててこそうかぶせもあれ",
    romaji: ["miosutetokosoukabusemoare"],
    score: 300,
  },
  {
    level: 3,
    kanji: "ミイラ取りがミイラになる",
    furigana: "みいらとりがみいらになる",
    romaji: ["miiratorigamiiraninaru"],
    score: 300,
  },
  {
    level: 3,
    kanji: "待てば海路の日和あり",
    furigana: "まてばかいろのひよりあり",
    romaji: ["matebakaironohiyoriari"],
    score: 300,
  },
  {
    level: 3,
    kanji: "藪をつついて蛇を出す",
    furigana: "やぶをつついてへびをだす",
    romaji: ["yabuwotutuitehebiwodasu"],
    score: 300,
  },
  {
    level: 3,
    kanji: "ローマは一日にしてならず",
    furigana: "ろーまはいちにちにしてならず",
    romaji: ["ro-mahaitinitinisitenarazu"],
    score: 300,
  },
  {
    level: 3,
    kanji: "渡る世間に鬼はない",
    furigana: "わたるせけんにおにはない",
    romaji: ["watarusekennnioniwanai"],
    score: 300,
  },
  {
    level: 3,
    kanji: "和をもって貴しとなす",
    furigana: "わをもってとうとしとなす",
    romaji: ["womottetoutositonasu"],
    score: 300,
  },
  {
    level: 3,
    kanji: "笑う門には福来る",
    furigana: "わらうかどにはふくきたる",
    romaji: ["waraukadonihahukukitaru", "waraukadonihafukukitaru"],
    score: 300,
  },
  {
    level: 3,
    kanji: "かわいい子には旅をさせよ",
    furigana: "かわいいこにはたびをさせよ",
    romaji: ["kawaiikonihatabiwosaseyo"],
    score: 300,
  },
];

export default level3;
